mod day_1;
mod day_1_2;
mod day_2;
mod day_2_2;
mod day_3;
mod day_3_2;
mod day_4;
mod day_4_2;
mod day_5;
mod day_6;
mod day_6_2;
mod day_6_2_faster;
mod day_7;
mod day_7_2;
mod day_8;
mod day_8_2;
mod day_9;
mod day_9_2;
mod day_10;
mod day_10_2;
mod day_11;
mod day_11_2;
mod day_12;

pub use crate::day_1::day_1_module;
pub use crate::day_1_2::day_1_2_module;
pub use crate::day_2::day_2_module;
pub use crate::day_2_2::day_2_2_module;
pub use crate::day_3::day_3_module;
pub use crate::day_3_2::day_3_2_module;
pub use crate::day_4::day_4_module;
pub use crate::day_4_2::day_4_2_module;
pub use crate::day_5::day_5_module;
pub use crate::day_6::day_6_module;
pub use crate::day_6_2::day_6_2_module;
pub use crate::day_6_2_faster::day_6_2_faster_module;
pub use crate::day_7::day_7_module;
pub use crate::day_7_2::day_7_2_module;
pub use crate::day_8::day_8_module;
pub use crate::day_8_2::day_8_2_module;
pub use crate::day_9::day_9_module;
pub use crate::day_9_2::day_9_2_module;
pub use crate::day_10::day_10_module;
pub use crate::day_10_2::day_10_2_module;
pub use crate::day_11::day_11_module;
pub use crate::day_11_2::day_11_2_module;
pub use crate::day_12::day_12_module;

fn main() {
    day_1_module::run();
    day_1_2_module::run();
    day_2_module::run();
    day_2_2_module::run();
    day_3_module::run();
    day_3_2_module::run();
    day_4_module::run();
    day_4_2_module::run();
    day_5_module::run();
    day_6_module::run();
    day_6_2_module::run();
    day_6_2_faster_module::run();
    day_7_module::run();
    day_7_2_module::run();
    day_8_module::run();
    day_8_2_module::run();
    day_9_module::run();
    day_9_2_module::run();
    day_10_module::run();
    day_10_2_module::run();
    day_11_module::run();
    day_11_2_module::run();
    day_12_module::run();
}
